### ISSUE TITLE
Always feedback restore system root

### ISSUE THREAD

**Issue by ixsam** [falafalafala1668/ContentCachingInVM#2]
I unzip the file and put it on the desktop folder, then in the recovery mode, use the cd command to reach the patch folder, and then press ./runme.sh apply <system root>, prompt me that the syntax is wrong. I try just ./runme.sh , it shows./RunMe.sh apply|restore <System Root>"

How to apply this patch?

**Comment by falafalafala1668** [comment]
New version fix it, you can try again.
Thanks.
